version: "3.9"

services:
  auth-service:
    build: ./services/auth-service
    ports:
      - "3001:3001"

  product-service:
    build: ./services/product-service
    ports:
      - "3002:3002"

  order-service:
    build: ./services/order-service
    ports:
      - "3003:3003"

  gateway:
    build: ./gateway
    ports:
      - "3000:3000"
